### ISSUE TITLE
allow usage in background 

### ISSUE THREAD

**Issue by rmawatson** [pauldemarco/flutter_blue#187]
Currently on android, startScan will fail when used in a background isolate as it it depends on registrant.activity() to be available, which in the case of background android service wont be.

Something like..

           ```
 case "startScan":
            {
                boolean hasPerms = (ContextCompat.checkSelfPermission(registrar.context(), Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED);

                if (registrar.activity() == null && !hasPerms) {
                    result.error("scan_error","bluetooth is not enabled",null);
                    break;
                }

                if (!hasPerms) {
                      ActivityCompat.requestPermissions...
```
is needed.

**Comment by alod2019** [comment]
in fact even plugin registration crashes if called from a background isolate
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
	at com.pauldemarco.flutterblue.FlutterBluePlugin.<init>(FlutterBluePlugin.java:89)
	at com.pauldemarco.flutterblue.FlutterBluePlugin.registerWith(FlutterBluePlugin.java:80)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:14)
```
