### ISSUE TITLE
BluetoothDevice.connect will emit two times if last time fail(timeout).

### ISSUE THREAD

**Issue by anakin-jin** [pauldemarco/flutter_blue#448]
my code:
`static Future<CBlufiClient> connect(BluetoothDevice device) async {
        var ts = DateTime.now().toString();
        return device.connect(timeout: Duration(seconds: 10)).then((v) {
            debugPrint("$ts:device connect return.");
            //get services and check if the device is valid ESP device
            return _getCorrectCharacteristic(device).then((vals) {
                if (vals == null || vals.length == 0)
                    return null;
                return CBlufiClient(device, vals[0], vals[1], vals[2]);
            }, onError: (s, e) {
                debugPrint("$ts:get charateristic error. $s,$e");
            });
        },onError: (s,e){
            debugPrint("$ts:connect error.$s,$e");
        });
    }`

below is running log
i bolded the connect event. 
i made two connection. the first one is fail bcz of timeout.  the second success but got two return instead of one i expected.
"I/flutter (12498): 2019-11-15 11:43:19.485242:device connect return."
"I/flutter (12498): 2019-11-15 11:43:45.953899:device connect return."

`D/BluetoothManager(12498): getConnectedDevices
**D/BluetoothGatt(12498): connect() - device: 30:AE:A4:CB:B0:46, auto: true**
D/BluetoothGatt(12498): registerApp()
D/BluetoothGatt(12498): registerApp() - UUID=4fcf6a51-d14b-46ec-8e8a-5c7b56b73f43
D/BluetoothGatt(12498): onClientRegistered() - status=0 clientIf=5
D/BluetoothManager(12498): getConnectionState()
D/BluetoothManager(12498): getConnectedDevices
E/flutter (12498): [ERROR:flutter/lib/ui/ui_dart_state.cc(144)] Unhandled Exception: TimeoutException after 0:00:10.000000: Failed to connect in time.
E/flutter (12498): #0      BluetoothDevice.connect.<anonymous closure> (package:flutter_blue/src/bluetooth_device.dart:33:9)
E/flutter (12498): #1      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (12498): #2      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12498): #3      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (12498): #4      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (12498): #5      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (12498): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12498): #7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (12498): #8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (12498): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (12498): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (12498): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (12498): 
D/BluetoothManager(12498): getConnectionState()
D/BluetoothManager(12498): getConnectedDevices
D/BluetoothGatt(12498): cancelOpen() - device: 30:AE:A4:CB:B0:46
D/BluetoothGatt(12498): close()
D/BluetoothGatt(12498): unregisterApp() - mClientIf=5
D/BluetoothManager(12498): getConnectedDevices
**D/BluetoothGatt(12498): connect() - device: 30:AE:A4:CB:B0:46, auto: true**
D/BluetoothGatt(12498): registerApp()
D/BluetoothGatt(12498): registerApp() - UUID=924079fd-7d90-47b0-9789-aa7dc5cbfe1b
D/BluetoothGatt(12498): onClientRegistered() - status=0 clientIf=5
D/BluetoothManager(12498): getConnectionState()
D/BluetoothManager(12498): getConnectedDevices
D/BluetoothGatt(12498): onClientConnectionState() - status=0 clientIf=5 device=30:AE:A4:CB:B0:46
D/FlutterBluePlugin(12498): [onConnectionStateChange] status: 0 newState: 2
I/flutter (12498): 2019-11-15 11:43:19.485242:device connect return.
D/BluetoothGatt(12498): discoverServices() - device: 30:AE:A4:CB:B0:46
I/flutter (12498): 2019-11-15 11:43:45.953899:device connect return.
D/BluetoothGatt(12498): discoverServices() - device: 30:AE:A4:CB:B0:46
D/BluetoothGatt(12498): onConnectionUpdated() - Device=30:AE:A4:CB:B0:46 interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(12498): onSearchComplete() = Device=30:AE:A4:CB:B0:46 Status=0
D/FlutterBluePlugin(12498): [onServicesDiscovered] count: 3 status: 0
I/flutter (12498): get services. 3
D/BluetoothGatt(12498): setCharacteristicNotification() - uuid: 0000ff02-0000-1000-8000-00805f9b34fb enable: true
D/BluetoothGatt(12498): onConnectionUpdated() - Device=30:AE:A4:CB:B0:46 interval=36 latency=0 timeout=500 status=0
I/flutter (12498): get services. 3
D/BluetoothGatt(12498): setCharacteristicNotification() - uuid: 0000ff02-0000-1000-8000-00805f9b34fb enable: true`

**Comment by anakin-jin** [comment]
another issue cause it. sorry
