### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: Too many elements

### ISSUE THREAD

**Issue by agnoam** [pauldemarco/flutter_blue#492]
Hi,
package version: `flutter_blue: 0.6.3+1`

I tried to search devices with this function:
```
Future<void> discoverDevices() async {
  FlutterBlue bluetooth = FlutterBlue.instance;
  if(await bluetooth.isAvailable && await bluetooth.isOn) {
	bluetooth.startScan(timeout: Duration(seconds: 5));
	print('scanning');

	bluetooth.scanResults.listen((scanRes) {
	  if(scanRes.length > 0) {
		print('found devices');
		setState(() => _scanResults = scanRes);
	  }
	},
	onDone: () => print('bluetooth scan done'),
	onError: (ex) => print('bluetooth scanning ex: $ex'));
  } else {
	if(!await bluetooth.isAvailable)
	  Dialogs.showAlert(context, 'This device does not support bluetooth');

	if(!await bluetooth.isOn)
	  Dialogs.showAlert(context, 'Please turn on bluetooth');
  }
}
```
But it allways returns an empty `List<ScanResult>`. 
So I tried to debug the flutter_blue package code and the package throws this exception.
```
I/chatty  (30587): uid=10347(com.agnoam.bluetooth_chat) 1.ui identical 4 lines
E/flutter (30587): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: Too many elements
E/flutter (30587): #0      Stream.single.<anonymous closure>  (dart:async/stream.dart:1322:15)
E/flutter (30587): #1      _rootRunUnary  (dart:async/zone.dart:1134:38)
E/flutter (30587): #2      _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter (30587): #3      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter (30587): #4      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
E/flutter (30587): #5      _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:266:7)
E/flutter (30587): #6      _SyncStreamControllerDispatch._sendData  (dart:async/stream_controller.dart:773:19)
E/flutter (30587): #7      _StreamController._add  (dart:async/stream_controller.dart:649:7)
E/flutter (30587): #8      _StreamController.add  (dart:async/stream_controller.dart:595:5)
E/flutter (30587): #9      _rootRunUnary  (dart:async/zone.dart:1134:38)
E/flutter (30587): #10     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter (30587): #11     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter (30587): #12     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
E/flutter (30587): #13     _DelayedData.perform  (dart:async/stream_impl.dart:594:14)
E/flutter (30587): #14     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:710:11)
E/flutter (30587): #15     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:670:7)
E/flutter (30587): #16     _rootRun  (dart:async/zone.dart:1122:38)
E/flutter (30587): #17     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (30587): #18     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (30587): #19     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter (30587): #20     _rootRun  (dart:async/zone.dart:1126:13)
E/flutter (30587): #21     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (30587): #22     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (30587): #23     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter (30587): #24     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter (30587): #25     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
E/flutter (30587):
D/BluetoothManager(30587): getConnectedDevices
```

**Comment by pauldemarco** [comment]
Interesting! Have you come up with a solution since posting
If not, can you please share the code that’s consuming the variable “_scanResults”?
