### ISSUE TITLE
NullPointerException when cancelling scanSubscription on android

### ISSUE THREAD

**Issue by lovasoa** [pauldemarco/flutter_blue#50]
In android, I got the following error while trying to stop scanning from my application: 

```
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): Failed to handle method call
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.stopScan(android.bluetooth.le.ScanCallback)' on a null object reference
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at com.pauldemarco.flutterblue.FlutterBluePlugin.stopScan21(FlutterBluePlugin.java:609)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at com.pauldemarco.flutterblue.FlutterBluePlugin.stopScan(FlutterBluePlugin.java:565)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at com.pauldemarco.flutterblue.FlutterBluePlugin.onMethodCall(FlutterBluePlugin.java:153)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:133)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(10734): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
D/BluetoothAdapter(10734): onBluetoothServiceDown: Sending callbacks to 1 clients
D/BluetoothAdapter(10734): onBluetoothServiceDown: Finished sending callbacks to registered clients
```

The problem here seems to be in [`stopScan21`](https://github.com/pauldemarco/flutter_blue/blob/master/android/src/main/java/com/pauldemarco/flutterblue/FlutterBluePlugin.java#L609), that doesn't check whether `mBluetoothAdapter.getBluetoothLeScanner()` returns null. There seems to be the same problem in [`startScan21`](https://github.com/pauldemarco/flutter_blue/blob/master/android/src/main/java/com/pauldemarco/flutterblue/FlutterBluePlugin.java#L604)

**Comment by pauldemarco** [comment]
`getBluetoothLeScanner()` returns null if the Adapter is not on.

I will wrap the NPE in an IllegalStateException and return that over the platform.

I'd like to consider standardizing error messages across the platform, maybe creating some set Error types, new issue will be created for this.
