### ISSUE TITLE
Headless mode on Jobscheduler throws: MissingPluginException(No implementation found for method isAvailable on channel)

### ISSUE THREAD

**Issue by gcervantes2005** [pauldemarco/flutter_blue#564]
Hello, I am running a Jobscheduler on Android to run the Scan method. 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)

My method is triggered by JobScheduler when app is killed and enters the following code:

```
void backgroundHeadlessTask(String taskId) async {
  print('Headless event receivedStart $taskId');
  try{
FlutterBlue flutterBlue = FlutterBlue.instance;
var subscription = flutterBlue.scanResults.listen((results) {
    // do something with scan results
    for (ScanResult r in results) {
        print('${r.device.name} found! rssi: ${r.rssi}');
    }
});
flutterBlue.stopScan();
  }catch(e)
  {
    print(e);
  }
  BackgroundFetch.finish(taskId);
}
```

When the app is killed and JobScheduler triggers to a Headles method I get:

04-30 23:34:55.210 24339 24376 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method isAvailable on channel plugins.pauldemarco.com/flutter_blue/methods)
04-30 23:34:55.210 24339 24376 E flutter : #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
04-30 23:34:55.210 24339 24376 E flutter : <asynchronous suspension>
04-30 23:34:55.210 24339 24376 E flutter : #1      FlutterBlue.isAvailable (package:flutter_blue/src/flutter_blue.dart:34:16)
04-30 23:34:55.210 24339 24376 E flutter : #2      FlutterBlue._setLogLevelIfAvailable (package:flutter_blue/src/flutter_blue.dart:70:15)
04-30 23:34:55.210 24339 24376 E flutter : #3      new FlutterBlue._ (package:flutter_blue/src/flutter_blue.dart:22:5)
04-30 23:34:55.210 24339 24376 E flutter : #4      FlutterBlue._instance (package:flutter_blue/src/flutter_blue.dart:25:38)
04-30 23:34:55.210 24339 24376 E flutter : #5      FlutterBlue._instance (package:flutter_blue/src/flutter_blue.dart:25:22)
04-30 23:34:55.210 24339 24376 E flutter : #6      FlutterBlue.instance (package:flutter_blue/src/flutter_blue.dart:26:38)
04-30 23:34:55.210 24339 24376 E flutter : #7      RadarController.scanBtDevices (package:covid_radar/controllers/RadarController.dart:68:43)
04-30 23:34:55.210 24339 24376 E flutter : #8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
04-30 23:34:55.210 24339 24376 E flutter : #9      _rootRunUnary (dart:async/zone.dart:1134:38)
04-30 23:34:55.210 24339 24376 E flutter : #10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
04-30 23:34:55.210 24339 24376 E flutter : #11     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
04-30 23:34:55.210 24339 24376 E flutter : #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
04-30 23:34:55.210 24339 24376 E flutter : #13     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
04-30 23:34:55.210 24339 24376 E flutter : #14     Future._completeWithValue (dart:async/future_impl.dart:524:5)

Does FlutterBlue support this headless task mode or app must be opened?

Regards

**Comment by VinniciusJesus** [comment]
any updates?
