### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ndevev** [pauldemarco/flutter_blue#587]
In v0.7.2 NullPointerException after CharacteristicWrite at FlutterBluePlugin.java:1004

`
[onConnectionStateChange] status: 19 newState: 0
D/FlutterBluePlugin( 4615): [onCharacteristicWrite] uuid: XXX status: 133
D/AndroidRuntime( 4615): Shutting down VM
D/FlutterBluePlugin( 4615): [onConnectionStateChange] status: 19 newState: 0
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 4615): 	at com.pauldemarco.flutter_blue.FlutterBluePlugin$5.run(FlutterBluePlugin.java:1004)
E/AndroidRuntime( 4615): 	at android.os.Handler.handleCallback(Handler.java:888)
E/AndroidRuntime( 4615): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 4615): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime( 4615): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
E/AndroidRuntime( 4615): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4615): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime( 4615): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/Process ( 4615): Sending signal. PID: 4615 SIG: 9
`

**Comment by Jbz797** [comment]
Same here
