### ISSUE TITLE
Activity io.flutter.embedding.android.FlutterActivity has leaked IntentReceiver com.pauldemarco.flutter_blue.FlutterBluePlugin$1$1@c0fd054 that was originally registered here. Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by laijinxian** [pauldemarco/flutter_blue#618]
```
E/ActivityThread(10556): Activity io.flutter.embedding.android.FlutterActivity has leaked IntentReceiver com.pauldemarco.flutter_blue.FlutterBluePlugin$1$1@c0fd054 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(10556): android.app.IntentReceiverLeaked: Activity io.flutter.embedding.android.FlutterActivity has leaked IntentReceiver com.pauldemarco.flutter_blue.FlutterBluePlugin$1$1@c0fd054 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(10556):        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1437)
E/ActivityThread(10556):        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1214)
E/ActivityThread(10556):        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1486)
E/ActivityThread(10556):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1459)
E/ActivityThread(10556):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1447)
E/ActivityThread(10556):        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:633)
E/ActivityThread(10556):        at com.pauldemarco.flutter_blue.FlutterBluePlugin$1.onListen(FlutterBluePlugin.java:731)
E/ActivityThread(10556):        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:193)
E/ActivityThread(10556):        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/ActivityThread(10556):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/ActivityThread(10556):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/ActivityThread(10556):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/ActivityThread(10556):        at android.os.MessageQueue.next(MessageQueue.java:326)
E/ActivityThread(10556):        at android.os.Looper.loop(Looper.java:165)
E/ActivityThread(10556):        at android.app.ActivityThread.main(ActivityThread.java:6806)
E/ActivityThread(10556):        at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(10556):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/ActivityThread(10556):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
W/ActivityThread(10556): handleWindowVisibility: no activity for token android.os.BinderProxy@5c39dc0
```
`When you click the return key of the mobile phone, this error will appear. The official example is the same. Why? How to solve it?`

**Comment by aknolldev** [comment]
Same here.

**Comment by gridar** [comment]
I think it's a duplicate of https://github.com/pauldemarco/flutter_blue/issues/228 ?
