### ISSUE TITLE
flutter_blue does not work on IOS device 

### ISSUE THREAD

**Issue by decolon** [pauldemarco/flutter_blue#670]
This seems to be related to #406, but starting a new thread since the old one is not very active. 

When I build with Android, I have no problems. When I build without flutter_blue in my pubspec, no problems. As soon as I add flutter_blue in my pubspec, and build for my iPhone, I get this error
```
Running "flutter pub get" in nobobo_pantry...
Launching lib/main.dart on iPhone (4) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 8R4KTRC86F
Running pod install...
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Exception: Error running pod install
CocoaPods' output:
↳
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

Finding Podfile changes
  A flutter_blue
  - Flutter
  - camera
  - cloud_firestore
  - firebase_auth
  - firebase_core
  - firebase_ml_vision
  - firebase_storage
  - flutter_exif_rotation
  - path_provider
  - vibration

Fetching external sources
-> Fetching podspec for `Flutter` from `Flutter`
-> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
-> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
-> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
-> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
-> Fetching podspec for `firebase_ml_vision` from `.symlinks/plugins/firebase_ml_vision/ios`
-> Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios`
-> Fetching podspec for `flutter_blue` from `.symlinks/plugins/flutter_blue/ios`
-> Fetching podspec for `flutter_exif_rotation` from `.symlinks/plugins/flutter_exif_rotation/ios`
-> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
-> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios`

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_6_3_6.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/6/3/6/FirebaseAuth/6.8.0/FirebaseAuth.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_e_c_d.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/e/c/d/Protobuf/4.0.0-rc1/Protobuf.podspec.json exists! Returning local because checking is only perfomed in repo update
[!] CocoaPods could not find compatible versions for pod "Protobuf":
  In snapshot (Podfile.lock):
    Protobuf (= 3.13.0, ~> 3.12)

  In Podfile:
    flutter_blue (from `.symlinks/plugins/flutter_blue/ios`) was resolved to 0.0.1, which depends on
      flutter_blue/Protos (= 0.0.1) was resolved to 0.0.1, which depends on
        Protobuf (~> 3.11.4)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Protobuf` inside your development pod `flutter_blue`.
   You should run `pod update Protobuf` to apply changes you've made.

/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
Here is my pubspec, Podfile, and Podfile.lock (all as .txt files)

[pubspec.yaml.txt](https://github.com/pauldemarco/flutter_blue/files/5177497/pubspec.yaml.txt)
[Podfile.lock.txt](https://github.com/pauldemarco/flutter_blue/files/5177498/Podfile.lock.txt)
[Podfile.txt](https://github.com/pauldemarco/flutter_blue/files/5177499/Podfile.txt)

From previous posts I have tried

    Removing ios and rebuilding with objc
    Removing ios and rebuilding with swift
    commenting out use_frameworks! in the Podfile
    commenting out ss.header_mappings_dir = "gen" from ios/.symlinks/flutter_blue/ios/flutter_blue.podspec
    updating Protobuf verions to ss.dependency "Protobuf", '~> 4.0.0-rc1' in ios/.symlinks/flutter_blue/ios/flutter_blue.podspec (i also tried version 3.12.0 and 3.13.0)
    using flutter_blue: git: git://github.com/pauldemarco/flutter_blue.git in my pubspec (see attached)
    using flutter_blue: ^0.7.2 in my pubspec

I have tried all these approaches 1 at a time, with no luck. Some dont seem to help flutter_blue, others seem to break other modules.

Any idea what I should try next?

For more housekeeping, here is my flutter doctor -v output
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.2 at /Users/bb-8/Workspace/SDKs/flutter
    • Framework revision bbfbf1770c (7 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/bb-8/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (1 available)
    • iPhone (4) (mobile) • 5ae9753c41cae0609366ed62da85ce52106a6082 • ios • iOS 13.6

• No issues found!
```

**Comment by LoveCcheng** [comment]
I have the same situation and it hasn't been resolved yet. Have you solved it yet?

**Comment by ju851zel** [comment]
Have you tried adding the package vie ```flutter_blue: ^0.8.0``` in the pubspec.yaml and not the git repo directly?

**Comment by RodrigoLScorza** [comment]
> Have you tried adding the package vie `flutter_blue: ^0.8.0` in the pubspec.yaml and not the git repo directly?

Yes, I did but have same problem

**Comment by devSumanrazz** [comment]
@pauldemarco Any fix on this?
