### ISSUE TITLE
Not working after building apk

### ISSUE THREAD

**Issue by praveenkprathap** [pauldemarco/flutter_blue#768]
Everything works fine in debug mode. when we build the apk it will not scan for devices.

This is the permissions I used are below.
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-feature android:name="android.hardware.bluetooth" />

**Comment by akash-flutterdev** [comment]
yes i am facing same issue, build apk not working
plz address issue

**Comment by akash-flutterdev** [comment]
just do this in android folder app/build.gradle

 `buildTypes {
        release {
            signingConfig signingConfigs.debug
            shrinkResources false
            minifyEnabled false
        }
    }`

**Comment by NaarGes** [comment]
I have the same problem
here is the log of error that happens on scan 

2021-02-24 02:49:15.840 1761-2088/? I/flutter: Error starting scan.
2021-02-24 02:49:15.840 1761-2088/? I/flutter: PlatformException(startScan, Field androidScanMode_ for b.e.a.s0 not found. Known fields are [private int b.e.a.s0.g, private b.d.d.b0$i b.e.a.s0.h, private boolean b.e.a.s0.i, private static final b.e.a.s0 b.e.a.s0.j, private static volatile b.d.d.a1 b.e.a.s0.k], java.lang.RuntimeException: Field androidScanMode_ for b.e.a.s0 not found. Known fields are [private int b.e.a.s0.g, private b.d.d.b0$i b.e.a.s0.h, private boolean b.e.a.s0.i, private static final b.e.a.s0 b.e.a.s0.j, private static volatile b.d.d.a1 b.e.a.s0.k]
        at b.d.d.v0.a(Unknown Source:72)
        at b.d.d.v0.a(Unknown Source:715)
        at b.d.d.v0.a(Unknown Source:12)
        at b.d.d.k0.a(Unknown Source:60)
        at b.d.d.k0.a(Unknown Source:49)
        at b.d.d.d1.a(Unknown Source:17)
        at b.d.d.d1.a(Unknown Source:4)
        at b.d.d.z$a.a(Unknown Source:9)
        at b.d.d.z$a.a(Unknown Source:4)
        at b.d.d.z$a.a(Unknown Source:0)
        at b.d.d.a$a.a(Unknown Source:2)
        at b.e.a.b.b(Unknown Source:10)
        at b.e.a.b.a(Unknown Source:1414)
        at f.a.c.a.j$a.a(Unknown Source:17)
    	at io.flutter.e

**Comment by yang6626** [comment]
how you fix it. bro

**Comment by akash-flutterdev** [comment]
ok sorry for late reply
here is solution just add in androidf/app/build.gradle

buildTypes {
    release {
        // TODO: Add your own signing config for the release build.
        // Signing with the debug keys for now, so `flutter run
--release` works.
        signingConfig signingConfigs.debug
        shrinkResources false
        minifyEnabled false
    }
}


 shrinkResources false
        minifyEnabled false

**Comment by afsanchez77** [comment]
Worked for me!
Thank you for sharing.

**Comment by cdExpat** [comment]
Worked for me too

Thanks alot

**Comment by spekary** [comment]
See #772

**Comment by biner88** [comment]
In the proguard-rules file, add a line:
 `-keep class com.pauldemarco.flutter_blue.** { *; }`

**Comment by spekary** [comment]
That worked

**Comment by akash-flutterdev** [comment]
thank u it's worked
