### ISSUE TITLE
startScan throws error in android only

### ISSUE THREAD

**Issue by rowdy15** [pauldemarco/flutter_blue#821]
The below error is recieved on an android phone when I start a scan (using suggested scan code)

error points to this part of the flutter_blue library

`    try {
      await _channel.invokeMethod('startScan', settings.writeToBuffer());
    } catch (e) {
      print('Error starting scan.');
      _stopScanPill.add(null);
      _isScanning.add(false);
      throw e;
    }`

`I/flutter (31217): about to scan
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): Failed to handle method call
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at com.pauldemarco.flutter_blue.FlutterBluePlugin.onMethodCall(FlutterBluePlugin.java:244)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at android.os.MessageQueue.next(MessageQueue.java:356)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at android.os.Looper.loop(Looper.java:138)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(31217): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
I/ProviderInstaller(31217): Installed default security provider GmsCore_OpenSSL
W/art     (31217): Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
W/art     (31217): Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
W/art     (31217): Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
I/flutter (31217): Error starting scan.
E/flutter (31217): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference
E/flutter (31217): 	at com.pauldemarco.flutter_blue.FlutterBluePlugin.onMethodCall(FlutterBluePlugin.java:244)
E/flutter (31217): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (31217): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (31217): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (31217): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31217): 	at android.os.MessageQueue.next(MessageQueue.java:356)
E/flutter (31217): 	at android.os.Looper.loop(Looper.java:138)
E/flutter (31217): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
E/flutter (31217): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31217): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/flutter (31217): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/flutter (31217): )
E/flutter (31217): #0      FlutterBlue.scan (package:flutter_blue/src/flutter_blue.dart:123:7)`

**Comment by rowdy15** [comment]
Solved my own problem.  It seems I needed to migrate the project to the new [V2 of the flutter embedding engine](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration).
