### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by JonYun** [pauldemarco/flutter_blue#835]
D/AndroidRuntime(18846): Shutting down VM
E/AndroidRuntime(18846): FATAL EXCEPTION: main
E/AndroidRuntime(18846): Process: com.pauldemarco.flutter_blue_example, PID: 18846
E/AndroidRuntime(18846): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseArray.size()' on a null object reference
E/AndroidRuntime(18846): 	at com.pauldemarco.flutter_blue.ProtoMaker.from(ProtoMaker.java:71)
E/AndroidRuntime(18846): 	at com.pauldemarco.flutter_blue.FlutterBluePlugin$2.onScanResult(FlutterBluePlugin.java:779)
E/AndroidRuntime(18846): 	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:512)
E/AndroidRuntime(18846): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(18846): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(18846): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(18846): 	at android.app.ActivityThread.main(ActivityThread.java:7590)
E/AndroidRuntime(18846): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18846): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(18846): 	at com.android.internal.os.ZygoteInit.mai

**Comment by JonYun** [comment]
my flutter version 2.0.6   dart version 2.12.3
