### ISSUE TITLE
Android stopped working Failed to handle method call

### ISSUE THREAD

**Issue by sboicu** [pauldemarco/flutter_blue#849]
V/AudioManager(21037): querySoundEffectsEnabled...
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): Failed to handle method call
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at com.pauldemarco.flutter_blue.FlutterBluePlugin.onMethodCall(FlutterBluePlugin.java:244)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at android.os.Looper.loop(Looper.java:176)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at android.app.ActivityThread.main(ActivityThread.java:8349)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#plugins.pauldemarco.com/flutter_blue/methods(21037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
I/flutter (21037): Error starting scan.
E/flutter (21037): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding.getActivity()' on a null object reference
E/flutter (21037): 	at com.pauldemarco.flutter_blue.FlutterBluePlugin.onMethodCall(FlutterBluePlugin.java:244)
E/flutter (21037): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (21037): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (21037): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (21037): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (21037): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter (21037): 	at android.os.Looper.loop(Looper.java:176)
E/flutter (21037): 	at android.app.ActivityThread.main(ActivityThread.java:8349)
E/flutter (21037): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (21037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/flutter (21037): )
E/flutter (21037): #0      FlutterBlue.scan (package:flutter_blue/src/flutter_blue.dart:123:7)
E/flutter (21037): <asynchronous suspension>
E/flutter (21037): 

there is no error on flutter doctor.
Up to yesterday everything was working well. today, while not modifying anything I cannot run the app anymore on android. everything works well on iOS

**Comment by arslanmughal99** [comment]
Did you find any solution for this ?
