### ISSUE TITLE
IOS: Unhandled Exception: Exception: Failed to write the characteristic

### ISSUE THREAD

**Issue by shunplus** [pauldemarco/flutter_blue#879]
didWriteValueForCharacteristic
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Exception: Failed to write the characteristic
#0      BluetoothCharacteristic.write.<anonymous closure> (package:flutter_blue/src/bluetooth_characteristic.dart:139:15)
#1      _rootRunUnary (dart:async/zone.dart:1362:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
<asynchronous suspension>
didUpdateNotificationStateForCharacteristic
 

Android is OK

**Comment by ShubhamAryanBansal** [comment]
yeah I am also facing the same issue on iOS... I have tried writing using :- utf8.encode("anyString") and with the given example by flutter_blue :- write([0x12, 0x34]) ..both are creating same error.
