### ISSUE TITLE
[ERROR]BufferUnderflowException after scanning bluetooth, app crashes

### ISSUE THREAD

**Issue by ram231** [pauldemarco/flutter_blue#91]
I am facing an error when part of my beacon is being scanned.
Tried to resolve it in your other solution but I have a different ERROR.
I have no clue where to trace this ERROR. It also works on your example, but after scanning my beacon gives an error. I'm using Samsung Galaxy Tab A and (beacon)SENSORO Smartbeacon-4aa

`E/AndroidRuntime(30488): Process: com.pauldemarco.flutterblueexample, PID: 30488
E/AndroidRuntime(30488): java.nio.BufferUnderflowException
E/AndroidRuntime(30488): 	at java.nio.ByteArrayBuffer.get(ByteArrayBuffer.java:152)
E/AndroidRuntime(30488): 	at com.pauldemarco.flutterblue.AdvertisementParser.parse(AdvertisementParser.java:55)
E/AndroidRuntime(30488): 	at com.pauldemarco.flutterblue.ProtoMaker.from(ProtoMaker.java:30)
E/AndroidRuntime(30488): 	at com.pauldemarco.flutterblue.FlutterBluePlugin$2.onScanResult(FlutterBluePlugin.java:625)
E/AndroidRuntime(30488): 	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:413)
E/AndroidRuntime(30488): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(30488): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(30488): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(30488): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
E/AndroidRuntime(30488): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30488): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1321)
E/AndroidRuntime(30488): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1211)`

**Comment by ram231** [comment]
[Closed] Issue #71 Although This was not included when I install the flutter_blue.
